---
on: push

jobs:
  test-ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
      - name: Install latest podman from Kubic repos
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL "https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key" \
            | gpg --dearmor \
            | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
              https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/ /" \
            | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
          sudo apt-get update -qq
          sudo apt-get -qq -y install podman
      - name: Show podman info
        run: podman info
      - name: Test podman
        run: podman run -it --rm alpine hostname
      - name: Install minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube version
      - name: Start cluster
        run: minikube start --profile test --driver podman --container-runtime cri-o
      - name: Profile list
        run: minikube profile list
      - name: Delete cluster
        run: minikube delete --profile test
  test-ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
      - name: Install latest podman from Kubic repos
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL "https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key" \
            | gpg --dearmor \
            | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
              https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/ /" \
            | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
          sudo apt-get update -qq
          sudo apt-get -qq -y install podman
      - name: Show podman info
        run: podman info
      - name: Test podman
        run: podman run -it --rm alpine hostname
      - name: Install minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube version
      - name: Start cluster
        run: minikube start --profile test --driver podman --container-runtime cri-o
      - name: Profile list
        run: minikube profile list
      - name: Delete cluster
        run: minikube delete --profile test
